# Generated by Django 4.2.3 on 2023-08-23 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0006_alter_favorite_options_alter_ingredient_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="units",
            new_name="measurement_unit",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="time",
            new_name="coocking_time",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
