# Generated by Django 4.2.3 on 2023-08-26 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_rename_coocking_time_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientsinrecipe",
            options={
                "verbose_name": "Ингредиенты в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
    ]
